inherit_from:
  - https://github.com/Alexander-Senko/Alexander-Senko/raw/refs/heads/main/.rubocop.yml
  - https://github.com/Alexander-Senko/Alexander-Senko/raw/refs/heads/main/.rubocop-rspec.yml

plugins:
  - rubocop-rake

Metrics/ModuleLength: # HACK: shared configuration gets ignored for some reason
  Exclude:
    - spec/**/*_spec.rb
