module Magic
	module Lookup
		module Namespaces
			def namespaces: -> Array[namespace]

			def                 for: (Module, ?namespace) -> Class?
			def namespaced_name_for: (Module, ?namespace) -> String
			def              match?: (Module, ?namespace) -> bool
			def         name_match?: (Module, ?namespace) -> bool
		end
	end
end
