module Magic
	module Lookup
		VERSION: String
		AUTHORS: Array[Gem::Author]

		def for: (Class, ?(Module | interned) namespace) -> Class?

		def name_for: (Module) -> String

		def descendants: -> Array[Class]
	end
end
