module Magic
	module Lookup
		VERSION: String
		AUTHORS: Array[Gem::Author]

		type namespace = Module | interned

		def                 for: (Module, ?namespace) -> Class?
		def            name_for: (Module)             -> String
		def namespaced_name_for: (Module, ?namespace) -> String
	end
end
